-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 13:17:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema appointment_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appointment_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appointment_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `appointment_db` ;

-- -----------------------------------------------------
-- Table `appointment_db`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointment_db`.`doctors` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `City` VARCHAR(255) NOT NULL,
  `Speciality` VARCHAR(255) NOT NULL,
  `Fees` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appointment_db`.`clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointment_db`.`clinics` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DOC_ID` INT(11) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  `Description` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DOC_ID_idx` (`DOC_ID` ASC) VISIBLE,
  CONSTRAINT `DOC_ID`
    FOREIGN KEY (`DOC_ID`)
    REFERENCES `appointment_db`.`doctors` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
